# Generated by Django 2.2.5 on 2019-12-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprojectrelation',
            name='project_id',
        ),
        migrations.AddField(
            model_name='employeeprojectrelation',
            name='project_id',
            field=models.ManyToManyField(to='employee.Projects'),
        ),
    ]
