# Generated by Django 2.2.5 on 2019-12-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20191224_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
