# Generated by Django 2.2.5 on 2019-12-25 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20191224_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprojectrelation',
            name='project_id',
        ),
        migrations.AddField(
            model_name='employeeprojectrelation',
            name='project_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.Projects'),
        ),
    ]
